### ISSUE TITLE
radar going away

### ISSUE THREAD

**Issue by mbates14** [vbguyny/ws4kp#48]
Just as a caution, radar.weather.com is going away and being replaced with something new, and is totally garbage, colors are puke, but I digress.

you will likely need to switch radar sources by next month. 

here is a new one: 
https://mesonet.agron.iastate.edu/archive/data/2020/11/15/GIS/uscomp/n0r_202011151910.png

**Comment by vbguyny** [comment]
Hello @mbates14 
Thank you so much for the heads up!  I had no idea that this was happening.  Strange because I am on a mail list that is supposed to let me know when items in NOAA are going to change.  I sent an email to my contact at NOAA to let me know if these changes will affect the FTP server that hosts the radar images that the WS4K+ uses.
Fingers crossed that no changes will be required!
Also thank you for providing an alternate link, however, it looks like I would need to implement logic to determine the parent folder based off of the date based off of UTC, I'm guessing.

**Comment by mbates14** [comment]
It wont be too bad, for example this gets you to the folder of the day: 

https://mesonet.agron.iastate.edu/archive/data/2020/11/15/GIS/uscomp/

But yea, you will need logic to know which year/month/day to navigate in.

Also, let me know what the NWS says.

**Comment by vbguyny** [comment]
@mbates14 you got it!  No word as of yet.

**Comment by vbguyny** [comment]
I still haven't received a response from NOAA.  They usually respond within 24 hours.  I am going to ping them again.

**Comment by mbates14** [comment]
its the government, that doesnt surprise me.

**Comment by vbguyny** [comment]
Update: I still haven't heard anything back from NOAA.  I even tried reaching out to the web master.

That being said, I tried to look at the images that the new radar site uses and they use a new API that returns 256x256 blocked images for a specific region of the US. I found documentation here: https://preview-opengeo.ncep.noaa.gov/geoserver/www/index.html and information about the response here: https://preview-opengeo.ncep.noaa.gov/geoserver/conus/conus_cref_raw/ows?service=wms&version=1.3.0&request=GetCapabilities

Further more, I found the new location of the raw precipitation radar image here:  https://mrms.ncep.noaa.gov/data/RIDGEII/L2/CONUS/CREF_RAW/

The bad news is that the new location the image is stored in a gzipped tiff which means I would need to implement new libraries to uncompressed and convert the image to PNG.  Also, it looks like the color ranges are different so that would need to be fixed as well.

**Comment by mbates14** [comment]
I guarantee they are doing this to keep bandwidth down. seems all the major radar websites load everything in tiles now. 

Also they might be making a move towards an enhanced radar where it can show all precip types.

**Comment by vbguyny** [comment]
The site now reads: **"On or about December 16, 2020"**
I think I am going to bite the bullet and just use the information from iastate.edu that you indicated.  It looks like the site has been around since 2012.  Hopefully it won't be going anywhere anytime soon...

**Comment by mbates14** [comment]
Today is the day. Curious whats gonna happen.

**Comment by vbguyny** [comment]
I just updated the site with v1.57 which now uses the alternate site that you indicated above.  The local radar no longer works in versions 1.56 and earlier.

I am actually surprised that they still went a head with the switch.  Also, I am upset that no one at NOAA/NWS was able to answer my question about whether or not they were going continue supporting the FTP site but I guess I got my answer!

@mbates14 thank you once again for both bringing this issue to my attention and also making me aware of the alternate source.  You are proof that not all heroes wear capes!

**Comment by mbates14** [comment]
Hey, i do what I can to help out where I can. 

BTW I think there's still a bug in your new routine, I noticed 2 radar images drawing on top of one another in the same canvas. 

Something to take a peek at. This was during animation by the way. Last 2 frames were superimposed.
