### ISSUE TITLE
Improved LDL

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#6]
I was thinking about a WeatherStar XL-style LDL. Here's a concept:
![noname](https://cloud.githubusercontent.com/assets/18102459/23638980/9329d5c8-02aa-11e7-8eec-1fa02157fa62.png)

**Comment by vbguyny** [comment]
I am not really following you.  Are you suggesting that the name of the location should always be visible?

**Comment by Psukeo** [comment]
Yeah, in the sorta way that the WSXL did it, as small text above the condition.

**Comment by vbguyny** [comment]
I have decided not to do this because of the following reasons:

1. This is a simulation of the WeatherStar 4000, not XL.
2. If someone wants to know what the current location is they can see it in the search box.

That being said, someone can always make a fork of my repo and add the feature themselves.

**Comment by Psukeo** [comment]
Honestly, I can see why now, as this would be a bit redundant if implemented, due to what you said. If I were to implement something from the XL into this, I'd rather have it be something that improves the forecast, like the Daypart Forecast or improved Latest Observations/Extended Forecast, rather than something stylistic.
