### ISSUE TITLE
Deployment with other webservers possible (e.g. Apache on Linux) ?

### ISSUE THREAD

**Issue by mmx1337** [vbguyny/ws4kp#62]
Hello!

I really appreciate the hard work you put into the project.  It looks great!

Quick question:  Do you know if anyone has tried this code with a different webserver?
I would like to try Apache on Linux.
Is there some proprietary feature of IIS that the code relies upon?

**Comment by vbguyny** [comment]
The code that @sparksterz is referring to is located here: https://github.com/vbguyny/ws4kp/blob/master/CORS/Default.aspx

**Comment by egftechman** [comment]
All you really need is a "CGI based" proxy server, the querystring in the CORS requests contain the URL it should fetch. Shouldn't be hard to implement with CURL in PHP or something.

**Comment by vbguyny** [comment]
@egftechman that would solve the CORS issue.  However, over the years there has been some routing and caching logic implemented to the Web Form as well.

**Comment by egftechman** [comment]
> @egftechman that would solve the CORS issue. However, over the years there has been some routing and caching logic implemented to the Web Form as well.

Yep, that's why I'm starting to write a backend to use NOAA Weather Wire Service and other "push" services to feed a PostGIS database (everything will be in there as points or outlines, counties and NWS zones would be converted to outlines, products without county, zone or state information would be the whole CWA of the issuing office), and the browser would just query the PostGIS server with the coordinates to get all the products for the point it's trying to display.
