### ISSUE TITLE
Naming Problem.

### ISSUE THREAD

**Issue by Psukeo** [vbguyny/ws4kp#7]
First pic is from Anchorage, particularly at a time when Soldotna was unavailable. Second pic, and the worst case in my eyes, is of Minneapolis.

![error](https://cloud.githubusercontent.com/assets/18102459/23779248/f49168a6-0504-11e7-8365-24f2c8bf1b58.png)
![errro](https://cloud.githubusercontent.com/assets/18102459/23779306/51b2cee4-0505-11e7-9fbc-a74378439631.png)

As you can tell, there are obvious repeats of the same city multiple times on the Latest Observations page. This makes it awfully confusing to others since they won't know which one is different. Please, rename them to reflect the district/airport they represent. Thank you.

With love,
 Tom

**Comment by vbguyny** [comment]
I fixed the issue with the duplicate city names in version 1.37

**Comment by mlbailey1308** [comment]
vbguyny,  I would like to use this for my website and tv station and would like to know if you can modify specifically for my location.  When I tested with my zip code, the extended forecast, almanac and local radar did not appear automatically.  zip code 38401.  Your help would be greatly appreciated.  Not sure if I can contact you off here or not.  I was referred to you by danny jessee for help.

**Comment by vbguyny** [comment]
Hello @mlbailey1308! It looks like NOAA is returning a malformatted XML response to my site.  I'll see if I can implement a work around for this issue.  I am happy to hear that you will be using it for your website and TV station!  Do you mind telling me where I can find them?

**Comment by mlbailey1308** [comment]
Currently, we are  moving station to Columbia, TN and are off the air.  One of the things we want to do is have a new weather channel running  local news and local weather.  Can you provide a bug free setting for Columbia, TN, Springhill, TN,  Franklin, TN, Lewisburg, TN that we can use for our TV broadcast.  I know that the w4000 simulator can be used but I am not a coder or programmer and need assistance with this.  Please let me know if you can help and at what cost.
Thanks in advance for your response.
Maurice

    On Wednesday, January 2, 2019, 8:58:34 PM EST, vbguyny <notifications@github.com> wrote:  
 
 
Hello @mlbailey1308! It looks like NOAA is returning a malformatted XML response to my site. I'll see if I can implement a work around for this issue. I am happy to hear that you will be using it for your website and TV station! Do you mind telling me where I can find them?

**Comment by vbguyny** [comment]
Gotcha.  Good luck in your station!

It looks like that from that list of cities you indicated that NOAA only reports Columbia, TN as having its own weather station.  The other cities will be pulling the weather from the nearest station according to NOAA.

As far as providing a "bug free" site, this is something that I cannot guarantee, mainly because:

1. I get information from 3rd party websites (NOAA, Wundground, etc) which can either go down or provide broken information (as in this case related to the issue you reported).
2. The website relies on a browser to render the information and some browsers display the information differently than others.
3. This site is more of a hobby than anything else. I already have a full time job so you might want to check out one of the [forks to this repo](https://github.com/vbguyny/ws4kp/network/members).

That being said, I'm looking into fixing this specific bug and should be fixed soon. Thanks.

**Comment by mlbailey1308** [comment]
I totally understand.  Is it possible you could provide me with a copy of what you have developed just for Columbia, with the audio and looping?  That would be a big help if you can?
Maurice

    On Wednesday, January 2, 2019, 9:45:49 PM EST, vbguyny <notifications@github.com> wrote:  
 
 
Gotcha. Good luck in your station!

It looks like that from that list of cities you indicated that NOAA only reports Columbia, TN as having its own weather station. The other cities will be pulling the weather from the nearest station according to NOAA.

As far as providing a "bug free" site, this is something that I cannot guarantee, mainly because:
   
   - I get information from 3rd party websites (NOAA, Wundground, etc) which can either go down or provide broken information (as in this case related to the issue you reported).
   - The website relies on a browser to render the information and some browsers display the information differently than others.
   - This site is more of a hobby than anything else. I already have a full time job so you might want to check out one of the forks to this repo.

That being said, I'm looking into fixing this specific bug and should be fixed soon. Thanks.

**Comment by vbguyny** [comment]
Of course! Once I have fixed the bug, you can download the entire website's source code clicking on this link: https://github.com/vbguyny/ws4kp/archive/master.zip
You will need to have someone to help set it up on a server running IIS 7.5 or later with ASP.NET 4.5 or later (refer to https://github.com/vbguyny/ws4kp/blob/master/README.md)

**Comment by mlbailey1308** [comment]
Thank you so very much!
Maurice

    On Wednesday, January 2, 2019, 9:58:07 PM EST, vbguyny <notifications@github.com> wrote:  
 
 
Of course! Once I have fixed the bug, you can download the entire website's source code clicking on this link: https://github.com/vbguyny/ws4kp/archive/master.zip
You will need to have someone to help set it up on a server running IIS 7.5 or later with ASP.NET 4.5 or later (refer to https://github.com/vbguyny/ws4kp/blob/master/README.md)

**Comment by vbguyny** [comment]
@mlbailey1308 this bug is fixed in version 1.39 which is now live: https://battaglia.ddns.net/twc/
