### ISSUE TITLE
Request for Linux Instructions

### ISSUE THREAD

**Issue by vivbyte** [vbguyny/ws4kp#94]
I am a Linux user and would like to request instructions or documentation for running the project on a Linux environment. The current instructions provided assume a Windows 10 environment, and I am specifically interested in running the project on Debian 12 (Bookworm).

It would be greatly appreciated if Linux-specific instructions could be provided, including any necessary dependencies, configuration steps, and considerations specific to Linux.

Thank you!

**Comment by vbguyny** [comment]
@vivbyte This project uses .NET Framework which doesn't run on native Linux. Look at this thread https://github.com/vbguyny/ws4kp/issues/81 to see how other people have got it working in Linux.

I also recommend taking a look at the following fork of the WS4K+ as it uses node.js instead of .NET to get everything working which I would imagine be more straight forward: https://github.com/netbymatt/ws4kp

**Comment by vivbyte** [comment]
I was able to get the nodejs fork working. Thanks so much!
